import os

print("[+] Installing requierments ...")
os.system('pip3 install termcolor')
os.system('pip3 install colorama')
os.system('pip3 install requests')
os.system('pip3 install rich')
os.system('pip3 install tgcrypto')
os.system('pip3 install IP2Location')
os.system('pip3 install pytz')
os.system('pip3 install licensing')
os.system('pip3 install pyfiglet')
os.system('pip3 uninstall -y setuptools')
os.system('pip3 install setuptools==66.0.0')
os.system('pip3 install pick')
os.system('pip3 install asyncio')
os.system('pip3 install configparser')
os.system('pip3 install lolpython')
os.system('pip3 install pyrogram')
os.system('pip3 install telethon')
os.system('pip3 install vobject')
os.system('pip3 install geopy')
os.system('pip3 install names')
os.system('pip3 install Faker')
os.system('pip3 install Faker')
os.system('pip3 install gender-guesser')

print("[+] setup complete !")
print("[+] now you can run any tool !")